package proto_template

var serverHandlerTemplateStr = `// Code generated by TX.
// Template: Proto Server Handler

package {{.ServerPackage}}
{{ if .ServerHImports }}
import (
{{- range .ServerHImports}}
    {{.}}
{{- end}}
{{ if .ServerImports }}
{{- range .ServerImports}}
    {{.}}
{{- end}}
{{end}}
){{end}}

func {{.ServerHandler}}() {
    //-----------------Handler Register------------------
{{- range .ClientCommands}}
    txws.RegisterHandler(uint16({{.ProtoName}}.{{.CmdName}}), {{.ProtoName}}.{{.ServerProto}}{}, {{- if .IsMessage}}nil,{{- else}}{{.ProtoName}}.{{.ClientProto}}{},{{- end}} {{.ExClientPackage}}.{{.ExClientFunc}}, "{{.ClientFunc}}" )
{{- end}}

    //-----------------Proto Register------------------
{{- range .ServerCommands}}
    txws.RegisterProto(uint16({{.ProtoName}}.{{.CmdName}}), {{.ProtoName}}.{{.ServerProto}}{})
{{- end}}
{{- range .ClientCommands}}
    txws.RegisterProto(uint16({{.ProtoName}}.{{.CmdName}}), {{.ProtoName}}.{{.ServerProto}}{})
{{- end}}
}
`

var serverFuncTemplateStr = `// Code generated by TX.
// Template: Proto Func Handler
// Generated at {{now}}

package {{.ExClientPackage}}
{{ if .ClientFImports }}
import (
{{- range .ClientFImports}}
    {{.}}
{{- end}}
){{end}}

func {{.ExClientFunc}}(req *txws.WsRequest) error {
    //xl.SInfow("{{.ExClientFunc}}, ", "UUID", req.WSClient().UUID(), "Message", req.Request().String())
    //dohPlayerImpl := req.WsPlayer().(*doh_player.DohPlayerImpl)
    //cokPlayer := req.WsPlayer().(*cok_player.CokPlayer)
    _ = req.Request().(*{{.ProtoName}}.{{.ServerProto}})
    {{if not .IsMessage}}_ = req.Response().(*{{.ProtoName}}.{{.ClientProto}}){{- end}}
    return nil
}
`
