// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc/actor_mgr.proto

#include "rpc/actor_mgr.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace actormgr {
PROTOBUF_CONSTEXPR CreateActorRequest::CreateActorRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.actor_id_)*/int64_t{0}
  , /*decltype(_impl_.actor_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateActorRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateActorRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateActorRequestDefaultTypeInternal() {}
  union {
    CreateActorRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateActorRequestDefaultTypeInternal _CreateActorRequest_default_instance_;
PROTOBUF_CONSTEXPR CreateActorReply::CreateActorReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_.error_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateActorReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateActorReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateActorReplyDefaultTypeInternal() {}
  union {
    CreateActorReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateActorReplyDefaultTypeInternal _CreateActorReply_default_instance_;
PROTOBUF_CONSTEXPR FindActorRequest::FindActorRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.actor_id_)*/int64_t{0}
  , /*decltype(_impl_.actor_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FindActorRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FindActorRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FindActorRequestDefaultTypeInternal() {}
  union {
    FindActorRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FindActorRequestDefaultTypeInternal _FindActorRequest_default_instance_;
PROTOBUF_CONSTEXPR FindActorReply::FindActorReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.found_)*/false
  , /*decltype(_impl_.remote_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FindActorReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FindActorReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FindActorReplyDefaultTypeInternal() {}
  union {
    FindActorReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FindActorReplyDefaultTypeInternal _FindActorReply_default_instance_;
PROTOBUF_CONSTEXPR UninstallActorRequest::UninstallActorRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.actor_id_)*/int64_t{0}
  , /*decltype(_impl_.actor_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UninstallActorRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UninstallActorRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UninstallActorRequestDefaultTypeInternal() {}
  union {
    UninstallActorRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UninstallActorRequestDefaultTypeInternal _UninstallActorRequest_default_instance_;
PROTOBUF_CONSTEXPR UninstallActorReply::UninstallActorReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_.error_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UninstallActorReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UninstallActorReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UninstallActorReplyDefaultTypeInternal() {}
  union {
    UninstallActorReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UninstallActorReplyDefaultTypeInternal _UninstallActorReply_default_instance_;
}  // namespace actormgr
static ::_pb::Metadata file_level_metadata_rpc_2factor_5fmgr_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_rpc_2factor_5fmgr_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_rpc_2factor_5fmgr_2eproto = nullptr;

const uint32_t TableStruct_rpc_2factor_5fmgr_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::actormgr::CreateActorRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::actormgr::CreateActorRequest, _impl_.actor_type_),
  PROTOBUF_FIELD_OFFSET(::actormgr::CreateActorRequest, _impl_.actor_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::actormgr::CreateActorReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::actormgr::CreateActorReply, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::actormgr::CreateActorReply, _impl_.error_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::actormgr::FindActorRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::actormgr::FindActorRequest, _impl_.actor_type_),
  PROTOBUF_FIELD_OFFSET(::actormgr::FindActorRequest, _impl_.actor_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::actormgr::FindActorReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::actormgr::FindActorReply, _impl_.found_),
  PROTOBUF_FIELD_OFFSET(::actormgr::FindActorReply, _impl_.remote_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::actormgr::UninstallActorRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::actormgr::UninstallActorRequest, _impl_.actor_type_),
  PROTOBUF_FIELD_OFFSET(::actormgr::UninstallActorRequest, _impl_.actor_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::actormgr::UninstallActorReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::actormgr::UninstallActorReply, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::actormgr::UninstallActorReply, _impl_.error_code_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::actormgr::CreateActorRequest)},
  { 8, -1, -1, sizeof(::actormgr::CreateActorReply)},
  { 16, -1, -1, sizeof(::actormgr::FindActorRequest)},
  { 24, -1, -1, sizeof(::actormgr::FindActorReply)},
  { 32, -1, -1, sizeof(::actormgr::UninstallActorRequest)},
  { 40, -1, -1, sizeof(::actormgr::UninstallActorReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::actormgr::_CreateActorRequest_default_instance_._instance,
  &::actormgr::_CreateActorReply_default_instance_._instance,
  &::actormgr::_FindActorRequest_default_instance_._instance,
  &::actormgr::_FindActorReply_default_instance_._instance,
  &::actormgr::_UninstallActorRequest_default_instance_._instance,
  &::actormgr::_UninstallActorReply_default_instance_._instance,
};

const char descriptor_table_protodef_rpc_2factor_5fmgr_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023rpc/actor_mgr.proto\022\010actormgr\":\n\022Creat"
  "eActorRequest\022\022\n\nactor_type\030\001 \001(\005\022\020\n\010act"
  "or_id\030\002 \001(\003\"7\n\020CreateActorReply\022\017\n\007succe"
  "ss\030\001 \001(\010\022\022\n\nerror_code\030\002 \001(\005\"8\n\020FindActo"
  "rRequest\022\022\n\nactor_type\030\001 \001(\005\022\020\n\010actor_id"
  "\030\002 \001(\003\"4\n\016FindActorReply\022\r\n\005found\030\001 \001(\010\022"
  "\023\n\013remote_type\030\002 \001(\005\"=\n\025UninstallActorRe"
  "quest\022\022\n\nactor_type\030\001 \001(\005\022\020\n\010actor_id\030\002 "
  "\001(\003\":\n\023UninstallActorReply\022\017\n\007success\030\001 "
  "\001(\010\022\022\n\nerror_code\030\002 \001(\0052\357\001\n\017ActorMgrServ"
  "ice\022G\n\013CreateActor\022\034.actormgr.CreateActo"
  "rRequest\032\032.actormgr.CreateActorReply\022A\n\t"
  "FindActor\022\032.actormgr.FindActorRequest\032\030."
  "actormgr.FindActorReply\022P\n\016UninstallActo"
  "r\022\037.actormgr.UninstallActorRequest\032\035.act"
  "ormgr.UninstallActorReplyb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_rpc_2factor_5fmgr_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rpc_2factor_5fmgr_2eproto = {
    false, false, 633, descriptor_table_protodef_rpc_2factor_5fmgr_2eproto,
    "rpc/actor_mgr.proto",
    &descriptor_table_rpc_2factor_5fmgr_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_rpc_2factor_5fmgr_2eproto::offsets,
    file_level_metadata_rpc_2factor_5fmgr_2eproto, file_level_enum_descriptors_rpc_2factor_5fmgr_2eproto,
    file_level_service_descriptors_rpc_2factor_5fmgr_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rpc_2factor_5fmgr_2eproto_getter() {
  return &descriptor_table_rpc_2factor_5fmgr_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rpc_2factor_5fmgr_2eproto(&descriptor_table_rpc_2factor_5fmgr_2eproto);
namespace actormgr {

// ===================================================================

class CreateActorRequest::_Internal {
 public:
};

CreateActorRequest::CreateActorRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:actormgr.CreateActorRequest)
}
CreateActorRequest::CreateActorRequest(const CreateActorRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateActorRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_id_){}
    , decltype(_impl_.actor_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.actor_id_, &from._impl_.actor_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.actor_type_) -
    reinterpret_cast<char*>(&_impl_.actor_id_)) + sizeof(_impl_.actor_type_));
  // @@protoc_insertion_point(copy_constructor:actormgr.CreateActorRequest)
}

inline void CreateActorRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_id_){int64_t{0}}
    , decltype(_impl_.actor_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CreateActorRequest::~CreateActorRequest() {
  // @@protoc_insertion_point(destructor:actormgr.CreateActorRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateActorRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CreateActorRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateActorRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:actormgr.CreateActorRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.actor_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.actor_type_) -
      reinterpret_cast<char*>(&_impl_.actor_id_)) + sizeof(_impl_.actor_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateActorRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 actor_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.actor_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 actor_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.actor_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateActorRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:actormgr.CreateActorRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 actor_type = 1;
  if (this->_internal_actor_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_actor_type(), target);
  }

  // int64 actor_id = 2;
  if (this->_internal_actor_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_actor_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:actormgr.CreateActorRequest)
  return target;
}

size_t CreateActorRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:actormgr.CreateActorRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 actor_id = 2;
  if (this->_internal_actor_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_actor_id());
  }

  // int32 actor_type = 1;
  if (this->_internal_actor_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_actor_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateActorRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateActorRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateActorRequest::GetClassData() const { return &_class_data_; }


void CreateActorRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateActorRequest*>(&to_msg);
  auto& from = static_cast<const CreateActorRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:actormgr.CreateActorRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_actor_id() != 0) {
    _this->_internal_set_actor_id(from._internal_actor_id());
  }
  if (from._internal_actor_type() != 0) {
    _this->_internal_set_actor_type(from._internal_actor_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateActorRequest::CopyFrom(const CreateActorRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:actormgr.CreateActorRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateActorRequest::IsInitialized() const {
  return true;
}

void CreateActorRequest::InternalSwap(CreateActorRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateActorRequest, _impl_.actor_type_)
      + sizeof(CreateActorRequest::_impl_.actor_type_)
      - PROTOBUF_FIELD_OFFSET(CreateActorRequest, _impl_.actor_id_)>(
          reinterpret_cast<char*>(&_impl_.actor_id_),
          reinterpret_cast<char*>(&other->_impl_.actor_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateActorRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_2factor_5fmgr_2eproto_getter, &descriptor_table_rpc_2factor_5fmgr_2eproto_once,
      file_level_metadata_rpc_2factor_5fmgr_2eproto[0]);
}

// ===================================================================

class CreateActorReply::_Internal {
 public:
};

CreateActorReply::CreateActorReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:actormgr.CreateActorReply)
}
CreateActorReply::CreateActorReply(const CreateActorReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateActorReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){}
    , decltype(_impl_.error_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.success_, &from._impl_.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.error_code_) -
    reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_code_));
  // @@protoc_insertion_point(copy_constructor:actormgr.CreateActorReply)
}

inline void CreateActorReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){false}
    , decltype(_impl_.error_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CreateActorReply::~CreateActorReply() {
  // @@protoc_insertion_point(destructor:actormgr.CreateActorReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateActorReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CreateActorReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateActorReply::Clear() {
// @@protoc_insertion_point(message_clear_start:actormgr.CreateActorReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.success_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.error_code_) -
      reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateActorReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 error_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.error_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateActorReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:actormgr.CreateActorReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // int32 error_code = 2;
  if (this->_internal_error_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_error_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:actormgr.CreateActorReply)
  return target;
}

size_t CreateActorReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:actormgr.CreateActorReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  // int32 error_code = 2;
  if (this->_internal_error_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_error_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateActorReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateActorReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateActorReply::GetClassData() const { return &_class_data_; }


void CreateActorReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateActorReply*>(&to_msg);
  auto& from = static_cast<const CreateActorReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:actormgr.CreateActorReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  if (from._internal_error_code() != 0) {
    _this->_internal_set_error_code(from._internal_error_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateActorReply::CopyFrom(const CreateActorReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:actormgr.CreateActorReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateActorReply::IsInitialized() const {
  return true;
}

void CreateActorReply::InternalSwap(CreateActorReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateActorReply, _impl_.error_code_)
      + sizeof(CreateActorReply::_impl_.error_code_)
      - PROTOBUF_FIELD_OFFSET(CreateActorReply, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateActorReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_2factor_5fmgr_2eproto_getter, &descriptor_table_rpc_2factor_5fmgr_2eproto_once,
      file_level_metadata_rpc_2factor_5fmgr_2eproto[1]);
}

// ===================================================================

class FindActorRequest::_Internal {
 public:
};

FindActorRequest::FindActorRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:actormgr.FindActorRequest)
}
FindActorRequest::FindActorRequest(const FindActorRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FindActorRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_id_){}
    , decltype(_impl_.actor_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.actor_id_, &from._impl_.actor_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.actor_type_) -
    reinterpret_cast<char*>(&_impl_.actor_id_)) + sizeof(_impl_.actor_type_));
  // @@protoc_insertion_point(copy_constructor:actormgr.FindActorRequest)
}

inline void FindActorRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_id_){int64_t{0}}
    , decltype(_impl_.actor_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FindActorRequest::~FindActorRequest() {
  // @@protoc_insertion_point(destructor:actormgr.FindActorRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FindActorRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void FindActorRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FindActorRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:actormgr.FindActorRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.actor_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.actor_type_) -
      reinterpret_cast<char*>(&_impl_.actor_id_)) + sizeof(_impl_.actor_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FindActorRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 actor_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.actor_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 actor_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.actor_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FindActorRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:actormgr.FindActorRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 actor_type = 1;
  if (this->_internal_actor_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_actor_type(), target);
  }

  // int64 actor_id = 2;
  if (this->_internal_actor_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_actor_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:actormgr.FindActorRequest)
  return target;
}

size_t FindActorRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:actormgr.FindActorRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 actor_id = 2;
  if (this->_internal_actor_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_actor_id());
  }

  // int32 actor_type = 1;
  if (this->_internal_actor_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_actor_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FindActorRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FindActorRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FindActorRequest::GetClassData() const { return &_class_data_; }


void FindActorRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FindActorRequest*>(&to_msg);
  auto& from = static_cast<const FindActorRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:actormgr.FindActorRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_actor_id() != 0) {
    _this->_internal_set_actor_id(from._internal_actor_id());
  }
  if (from._internal_actor_type() != 0) {
    _this->_internal_set_actor_type(from._internal_actor_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FindActorRequest::CopyFrom(const FindActorRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:actormgr.FindActorRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FindActorRequest::IsInitialized() const {
  return true;
}

void FindActorRequest::InternalSwap(FindActorRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FindActorRequest, _impl_.actor_type_)
      + sizeof(FindActorRequest::_impl_.actor_type_)
      - PROTOBUF_FIELD_OFFSET(FindActorRequest, _impl_.actor_id_)>(
          reinterpret_cast<char*>(&_impl_.actor_id_),
          reinterpret_cast<char*>(&other->_impl_.actor_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FindActorRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_2factor_5fmgr_2eproto_getter, &descriptor_table_rpc_2factor_5fmgr_2eproto_once,
      file_level_metadata_rpc_2factor_5fmgr_2eproto[2]);
}

// ===================================================================

class FindActorReply::_Internal {
 public:
};

FindActorReply::FindActorReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:actormgr.FindActorReply)
}
FindActorReply::FindActorReply(const FindActorReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FindActorReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.found_){}
    , decltype(_impl_.remote_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.found_, &from._impl_.found_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.remote_type_) -
    reinterpret_cast<char*>(&_impl_.found_)) + sizeof(_impl_.remote_type_));
  // @@protoc_insertion_point(copy_constructor:actormgr.FindActorReply)
}

inline void FindActorReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.found_){false}
    , decltype(_impl_.remote_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FindActorReply::~FindActorReply() {
  // @@protoc_insertion_point(destructor:actormgr.FindActorReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FindActorReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void FindActorReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FindActorReply::Clear() {
// @@protoc_insertion_point(message_clear_start:actormgr.FindActorReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.found_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.remote_type_) -
      reinterpret_cast<char*>(&_impl_.found_)) + sizeof(_impl_.remote_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FindActorReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool found = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.found_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 remote_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.remote_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FindActorReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:actormgr.FindActorReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool found = 1;
  if (this->_internal_found() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_found(), target);
  }

  // int32 remote_type = 2;
  if (this->_internal_remote_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_remote_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:actormgr.FindActorReply)
  return target;
}

size_t FindActorReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:actormgr.FindActorReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool found = 1;
  if (this->_internal_found() != 0) {
    total_size += 1 + 1;
  }

  // int32 remote_type = 2;
  if (this->_internal_remote_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_remote_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FindActorReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FindActorReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FindActorReply::GetClassData() const { return &_class_data_; }


void FindActorReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FindActorReply*>(&to_msg);
  auto& from = static_cast<const FindActorReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:actormgr.FindActorReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_found() != 0) {
    _this->_internal_set_found(from._internal_found());
  }
  if (from._internal_remote_type() != 0) {
    _this->_internal_set_remote_type(from._internal_remote_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FindActorReply::CopyFrom(const FindActorReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:actormgr.FindActorReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FindActorReply::IsInitialized() const {
  return true;
}

void FindActorReply::InternalSwap(FindActorReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FindActorReply, _impl_.remote_type_)
      + sizeof(FindActorReply::_impl_.remote_type_)
      - PROTOBUF_FIELD_OFFSET(FindActorReply, _impl_.found_)>(
          reinterpret_cast<char*>(&_impl_.found_),
          reinterpret_cast<char*>(&other->_impl_.found_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FindActorReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_2factor_5fmgr_2eproto_getter, &descriptor_table_rpc_2factor_5fmgr_2eproto_once,
      file_level_metadata_rpc_2factor_5fmgr_2eproto[3]);
}

// ===================================================================

class UninstallActorRequest::_Internal {
 public:
};

UninstallActorRequest::UninstallActorRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:actormgr.UninstallActorRequest)
}
UninstallActorRequest::UninstallActorRequest(const UninstallActorRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UninstallActorRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_id_){}
    , decltype(_impl_.actor_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.actor_id_, &from._impl_.actor_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.actor_type_) -
    reinterpret_cast<char*>(&_impl_.actor_id_)) + sizeof(_impl_.actor_type_));
  // @@protoc_insertion_point(copy_constructor:actormgr.UninstallActorRequest)
}

inline void UninstallActorRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_id_){int64_t{0}}
    , decltype(_impl_.actor_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UninstallActorRequest::~UninstallActorRequest() {
  // @@protoc_insertion_point(destructor:actormgr.UninstallActorRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UninstallActorRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UninstallActorRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UninstallActorRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:actormgr.UninstallActorRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.actor_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.actor_type_) -
      reinterpret_cast<char*>(&_impl_.actor_id_)) + sizeof(_impl_.actor_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UninstallActorRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 actor_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.actor_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 actor_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.actor_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UninstallActorRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:actormgr.UninstallActorRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 actor_type = 1;
  if (this->_internal_actor_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_actor_type(), target);
  }

  // int64 actor_id = 2;
  if (this->_internal_actor_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_actor_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:actormgr.UninstallActorRequest)
  return target;
}

size_t UninstallActorRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:actormgr.UninstallActorRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 actor_id = 2;
  if (this->_internal_actor_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_actor_id());
  }

  // int32 actor_type = 1;
  if (this->_internal_actor_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_actor_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UninstallActorRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UninstallActorRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UninstallActorRequest::GetClassData() const { return &_class_data_; }


void UninstallActorRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UninstallActorRequest*>(&to_msg);
  auto& from = static_cast<const UninstallActorRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:actormgr.UninstallActorRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_actor_id() != 0) {
    _this->_internal_set_actor_id(from._internal_actor_id());
  }
  if (from._internal_actor_type() != 0) {
    _this->_internal_set_actor_type(from._internal_actor_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UninstallActorRequest::CopyFrom(const UninstallActorRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:actormgr.UninstallActorRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UninstallActorRequest::IsInitialized() const {
  return true;
}

void UninstallActorRequest::InternalSwap(UninstallActorRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UninstallActorRequest, _impl_.actor_type_)
      + sizeof(UninstallActorRequest::_impl_.actor_type_)
      - PROTOBUF_FIELD_OFFSET(UninstallActorRequest, _impl_.actor_id_)>(
          reinterpret_cast<char*>(&_impl_.actor_id_),
          reinterpret_cast<char*>(&other->_impl_.actor_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UninstallActorRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_2factor_5fmgr_2eproto_getter, &descriptor_table_rpc_2factor_5fmgr_2eproto_once,
      file_level_metadata_rpc_2factor_5fmgr_2eproto[4]);
}

// ===================================================================

class UninstallActorReply::_Internal {
 public:
};

UninstallActorReply::UninstallActorReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:actormgr.UninstallActorReply)
}
UninstallActorReply::UninstallActorReply(const UninstallActorReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UninstallActorReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){}
    , decltype(_impl_.error_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.success_, &from._impl_.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.error_code_) -
    reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_code_));
  // @@protoc_insertion_point(copy_constructor:actormgr.UninstallActorReply)
}

inline void UninstallActorReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){false}
    , decltype(_impl_.error_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UninstallActorReply::~UninstallActorReply() {
  // @@protoc_insertion_point(destructor:actormgr.UninstallActorReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UninstallActorReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UninstallActorReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UninstallActorReply::Clear() {
// @@protoc_insertion_point(message_clear_start:actormgr.UninstallActorReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.success_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.error_code_) -
      reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UninstallActorReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 error_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.error_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UninstallActorReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:actormgr.UninstallActorReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // int32 error_code = 2;
  if (this->_internal_error_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_error_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:actormgr.UninstallActorReply)
  return target;
}

size_t UninstallActorReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:actormgr.UninstallActorReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  // int32 error_code = 2;
  if (this->_internal_error_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_error_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UninstallActorReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UninstallActorReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UninstallActorReply::GetClassData() const { return &_class_data_; }


void UninstallActorReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UninstallActorReply*>(&to_msg);
  auto& from = static_cast<const UninstallActorReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:actormgr.UninstallActorReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  if (from._internal_error_code() != 0) {
    _this->_internal_set_error_code(from._internal_error_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UninstallActorReply::CopyFrom(const UninstallActorReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:actormgr.UninstallActorReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UninstallActorReply::IsInitialized() const {
  return true;
}

void UninstallActorReply::InternalSwap(UninstallActorReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UninstallActorReply, _impl_.error_code_)
      + sizeof(UninstallActorReply::_impl_.error_code_)
      - PROTOBUF_FIELD_OFFSET(UninstallActorReply, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UninstallActorReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_2factor_5fmgr_2eproto_getter, &descriptor_table_rpc_2factor_5fmgr_2eproto_once,
      file_level_metadata_rpc_2factor_5fmgr_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace actormgr
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::actormgr::CreateActorRequest*
Arena::CreateMaybeMessage< ::actormgr::CreateActorRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::actormgr::CreateActorRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::actormgr::CreateActorReply*
Arena::CreateMaybeMessage< ::actormgr::CreateActorReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::actormgr::CreateActorReply >(arena);
}
template<> PROTOBUF_NOINLINE ::actormgr::FindActorRequest*
Arena::CreateMaybeMessage< ::actormgr::FindActorRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::actormgr::FindActorRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::actormgr::FindActorReply*
Arena::CreateMaybeMessage< ::actormgr::FindActorReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::actormgr::FindActorReply >(arena);
}
template<> PROTOBUF_NOINLINE ::actormgr::UninstallActorRequest*
Arena::CreateMaybeMessage< ::actormgr::UninstallActorRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::actormgr::UninstallActorRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::actormgr::UninstallActorReply*
Arena::CreateMaybeMessage< ::actormgr::UninstallActorReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::actormgr::UninstallActorReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
