// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc/actor_mgr.proto

#include "rpc/actor_mgr.pb.h"
#include "rpc/actor_mgr.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace actormgr {

static const char* ActorMgrService_method_names[] = {
  "/actormgr.ActorMgrService/CreateActor",
  "/actormgr.ActorMgrService/FindActor",
  "/actormgr.ActorMgrService/UninstallActor",
};

std::unique_ptr< ActorMgrService::Stub> ActorMgrService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ActorMgrService::Stub> stub(new ActorMgrService::Stub(channel, options));
  return stub;
}

ActorMgrService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateActor_(ActorMgrService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindActor_(ActorMgrService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UninstallActor_(ActorMgrService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ActorMgrService::Stub::CreateActor(::grpc::ClientContext* context, const ::actormgr::CreateActorRequest& request, ::actormgr::CreateActorReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::actormgr::CreateActorRequest, ::actormgr::CreateActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateActor_, context, request, response);
}

void ActorMgrService::Stub::async::CreateActor(::grpc::ClientContext* context, const ::actormgr::CreateActorRequest* request, ::actormgr::CreateActorReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::actormgr::CreateActorRequest, ::actormgr::CreateActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateActor_, context, request, response, std::move(f));
}

void ActorMgrService::Stub::async::CreateActor(::grpc::ClientContext* context, const ::actormgr::CreateActorRequest* request, ::actormgr::CreateActorReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::actormgr::CreateActorReply>* ActorMgrService::Stub::PrepareAsyncCreateActorRaw(::grpc::ClientContext* context, const ::actormgr::CreateActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::actormgr::CreateActorReply, ::actormgr::CreateActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::actormgr::CreateActorReply>* ActorMgrService::Stub::AsyncCreateActorRaw(::grpc::ClientContext* context, const ::actormgr::CreateActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ActorMgrService::Stub::FindActor(::grpc::ClientContext* context, const ::actormgr::FindActorRequest& request, ::actormgr::FindActorReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::actormgr::FindActorRequest, ::actormgr::FindActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindActor_, context, request, response);
}

void ActorMgrService::Stub::async::FindActor(::grpc::ClientContext* context, const ::actormgr::FindActorRequest* request, ::actormgr::FindActorReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::actormgr::FindActorRequest, ::actormgr::FindActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindActor_, context, request, response, std::move(f));
}

void ActorMgrService::Stub::async::FindActor(::grpc::ClientContext* context, const ::actormgr::FindActorRequest* request, ::actormgr::FindActorReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::actormgr::FindActorReply>* ActorMgrService::Stub::PrepareAsyncFindActorRaw(::grpc::ClientContext* context, const ::actormgr::FindActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::actormgr::FindActorReply, ::actormgr::FindActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::actormgr::FindActorReply>* ActorMgrService::Stub::AsyncFindActorRaw(::grpc::ClientContext* context, const ::actormgr::FindActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ActorMgrService::Stub::UninstallActor(::grpc::ClientContext* context, const ::actormgr::UninstallActorRequest& request, ::actormgr::UninstallActorReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::actormgr::UninstallActorRequest, ::actormgr::UninstallActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UninstallActor_, context, request, response);
}

void ActorMgrService::Stub::async::UninstallActor(::grpc::ClientContext* context, const ::actormgr::UninstallActorRequest* request, ::actormgr::UninstallActorReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::actormgr::UninstallActorRequest, ::actormgr::UninstallActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UninstallActor_, context, request, response, std::move(f));
}

void ActorMgrService::Stub::async::UninstallActor(::grpc::ClientContext* context, const ::actormgr::UninstallActorRequest* request, ::actormgr::UninstallActorReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UninstallActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::actormgr::UninstallActorReply>* ActorMgrService::Stub::PrepareAsyncUninstallActorRaw(::grpc::ClientContext* context, const ::actormgr::UninstallActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::actormgr::UninstallActorReply, ::actormgr::UninstallActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UninstallActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::actormgr::UninstallActorReply>* ActorMgrService::Stub::AsyncUninstallActorRaw(::grpc::ClientContext* context, const ::actormgr::UninstallActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUninstallActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

ActorMgrService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ActorMgrService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ActorMgrService::Service, ::actormgr::CreateActorRequest, ::actormgr::CreateActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ActorMgrService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::actormgr::CreateActorRequest* req,
             ::actormgr::CreateActorReply* resp) {
               return service->CreateActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ActorMgrService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ActorMgrService::Service, ::actormgr::FindActorRequest, ::actormgr::FindActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ActorMgrService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::actormgr::FindActorRequest* req,
             ::actormgr::FindActorReply* resp) {
               return service->FindActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ActorMgrService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ActorMgrService::Service, ::actormgr::UninstallActorRequest, ::actormgr::UninstallActorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ActorMgrService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::actormgr::UninstallActorRequest* req,
             ::actormgr::UninstallActorReply* resp) {
               return service->UninstallActor(ctx, req, resp);
             }, this)));
}

ActorMgrService::Service::~Service() {
}

::grpc::Status ActorMgrService::Service::CreateActor(::grpc::ServerContext* context, const ::actormgr::CreateActorRequest* request, ::actormgr::CreateActorReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ActorMgrService::Service::FindActor(::grpc::ServerContext* context, const ::actormgr::FindActorRequest* request, ::actormgr::FindActorReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ActorMgrService::Service::UninstallActor(::grpc::ServerContext* context, const ::actormgr::UninstallActorRequest* request, ::actormgr::UninstallActorReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace actormgr

