// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc/actor_mgr.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_2factor_5fmgr_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpc_2factor_5fmgr_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpc_2factor_5fmgr_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_2factor_5fmgr_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpc_2factor_5fmgr_2eproto;
namespace actormgr {
class CreateActorReply;
struct CreateActorReplyDefaultTypeInternal;
extern CreateActorReplyDefaultTypeInternal _CreateActorReply_default_instance_;
class CreateActorRequest;
struct CreateActorRequestDefaultTypeInternal;
extern CreateActorRequestDefaultTypeInternal _CreateActorRequest_default_instance_;
class FindActorReply;
struct FindActorReplyDefaultTypeInternal;
extern FindActorReplyDefaultTypeInternal _FindActorReply_default_instance_;
class FindActorRequest;
struct FindActorRequestDefaultTypeInternal;
extern FindActorRequestDefaultTypeInternal _FindActorRequest_default_instance_;
class UninstallActorReply;
struct UninstallActorReplyDefaultTypeInternal;
extern UninstallActorReplyDefaultTypeInternal _UninstallActorReply_default_instance_;
class UninstallActorRequest;
struct UninstallActorRequestDefaultTypeInternal;
extern UninstallActorRequestDefaultTypeInternal _UninstallActorRequest_default_instance_;
}  // namespace actormgr
PROTOBUF_NAMESPACE_OPEN
template<> ::actormgr::CreateActorReply* Arena::CreateMaybeMessage<::actormgr::CreateActorReply>(Arena*);
template<> ::actormgr::CreateActorRequest* Arena::CreateMaybeMessage<::actormgr::CreateActorRequest>(Arena*);
template<> ::actormgr::FindActorReply* Arena::CreateMaybeMessage<::actormgr::FindActorReply>(Arena*);
template<> ::actormgr::FindActorRequest* Arena::CreateMaybeMessage<::actormgr::FindActorRequest>(Arena*);
template<> ::actormgr::UninstallActorReply* Arena::CreateMaybeMessage<::actormgr::UninstallActorReply>(Arena*);
template<> ::actormgr::UninstallActorRequest* Arena::CreateMaybeMessage<::actormgr::UninstallActorRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace actormgr {

// ===================================================================

class CreateActorRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:actormgr.CreateActorRequest) */ {
 public:
  inline CreateActorRequest() : CreateActorRequest(nullptr) {}
  ~CreateActorRequest() override;
  explicit PROTOBUF_CONSTEXPR CreateActorRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreateActorRequest(const CreateActorRequest& from);
  CreateActorRequest(CreateActorRequest&& from) noexcept
    : CreateActorRequest() {
    *this = ::std::move(from);
  }

  inline CreateActorRequest& operator=(const CreateActorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateActorRequest& operator=(CreateActorRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateActorRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreateActorRequest* internal_default_instance() {
    return reinterpret_cast<const CreateActorRequest*>(
               &_CreateActorRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CreateActorRequest& a, CreateActorRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateActorRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateActorRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateActorRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreateActorRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreateActorRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CreateActorRequest& from) {
    CreateActorRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateActorRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "actormgr.CreateActorRequest";
  }
  protected:
  explicit CreateActorRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActorIdFieldNumber = 2,
    kActorTypeFieldNumber = 1,
  };
  // int64 actor_id = 2;
  void clear_actor_id();
  int64_t actor_id() const;
  void set_actor_id(int64_t value);
  private:
  int64_t _internal_actor_id() const;
  void _internal_set_actor_id(int64_t value);
  public:

  // int32 actor_type = 1;
  void clear_actor_type();
  int32_t actor_type() const;
  void set_actor_type(int32_t value);
  private:
  int32_t _internal_actor_type() const;
  void _internal_set_actor_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:actormgr.CreateActorRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t actor_id_;
    int32_t actor_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2factor_5fmgr_2eproto;
};
// -------------------------------------------------------------------

class CreateActorReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:actormgr.CreateActorReply) */ {
 public:
  inline CreateActorReply() : CreateActorReply(nullptr) {}
  ~CreateActorReply() override;
  explicit PROTOBUF_CONSTEXPR CreateActorReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreateActorReply(const CreateActorReply& from);
  CreateActorReply(CreateActorReply&& from) noexcept
    : CreateActorReply() {
    *this = ::std::move(from);
  }

  inline CreateActorReply& operator=(const CreateActorReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateActorReply& operator=(CreateActorReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateActorReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreateActorReply* internal_default_instance() {
    return reinterpret_cast<const CreateActorReply*>(
               &_CreateActorReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CreateActorReply& a, CreateActorReply& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateActorReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateActorReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateActorReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreateActorReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreateActorReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CreateActorReply& from) {
    CreateActorReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateActorReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "actormgr.CreateActorReply";
  }
  protected:
  explicit CreateActorReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
    kErrorCodeFieldNumber = 2,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 error_code = 2;
  void clear_error_code();
  int32_t error_code() const;
  void set_error_code(int32_t value);
  private:
  int32_t _internal_error_code() const;
  void _internal_set_error_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:actormgr.CreateActorReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    int32_t error_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2factor_5fmgr_2eproto;
};
// -------------------------------------------------------------------

class FindActorRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:actormgr.FindActorRequest) */ {
 public:
  inline FindActorRequest() : FindActorRequest(nullptr) {}
  ~FindActorRequest() override;
  explicit PROTOBUF_CONSTEXPR FindActorRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FindActorRequest(const FindActorRequest& from);
  FindActorRequest(FindActorRequest&& from) noexcept
    : FindActorRequest() {
    *this = ::std::move(from);
  }

  inline FindActorRequest& operator=(const FindActorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FindActorRequest& operator=(FindActorRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FindActorRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FindActorRequest* internal_default_instance() {
    return reinterpret_cast<const FindActorRequest*>(
               &_FindActorRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FindActorRequest& a, FindActorRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FindActorRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FindActorRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FindActorRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FindActorRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FindActorRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FindActorRequest& from) {
    FindActorRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FindActorRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "actormgr.FindActorRequest";
  }
  protected:
  explicit FindActorRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActorIdFieldNumber = 2,
    kActorTypeFieldNumber = 1,
  };
  // int64 actor_id = 2;
  void clear_actor_id();
  int64_t actor_id() const;
  void set_actor_id(int64_t value);
  private:
  int64_t _internal_actor_id() const;
  void _internal_set_actor_id(int64_t value);
  public:

  // int32 actor_type = 1;
  void clear_actor_type();
  int32_t actor_type() const;
  void set_actor_type(int32_t value);
  private:
  int32_t _internal_actor_type() const;
  void _internal_set_actor_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:actormgr.FindActorRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t actor_id_;
    int32_t actor_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2factor_5fmgr_2eproto;
};
// -------------------------------------------------------------------

class FindActorReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:actormgr.FindActorReply) */ {
 public:
  inline FindActorReply() : FindActorReply(nullptr) {}
  ~FindActorReply() override;
  explicit PROTOBUF_CONSTEXPR FindActorReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FindActorReply(const FindActorReply& from);
  FindActorReply(FindActorReply&& from) noexcept
    : FindActorReply() {
    *this = ::std::move(from);
  }

  inline FindActorReply& operator=(const FindActorReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline FindActorReply& operator=(FindActorReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FindActorReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const FindActorReply* internal_default_instance() {
    return reinterpret_cast<const FindActorReply*>(
               &_FindActorReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FindActorReply& a, FindActorReply& b) {
    a.Swap(&b);
  }
  inline void Swap(FindActorReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FindActorReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FindActorReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FindActorReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FindActorReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FindActorReply& from) {
    FindActorReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FindActorReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "actormgr.FindActorReply";
  }
  protected:
  explicit FindActorReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFoundFieldNumber = 1,
    kRemoteTypeFieldNumber = 2,
  };
  // bool found = 1;
  void clear_found();
  bool found() const;
  void set_found(bool value);
  private:
  bool _internal_found() const;
  void _internal_set_found(bool value);
  public:

  // int32 remote_type = 2;
  void clear_remote_type();
  int32_t remote_type() const;
  void set_remote_type(int32_t value);
  private:
  int32_t _internal_remote_type() const;
  void _internal_set_remote_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:actormgr.FindActorReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool found_;
    int32_t remote_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2factor_5fmgr_2eproto;
};
// -------------------------------------------------------------------

class UninstallActorRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:actormgr.UninstallActorRequest) */ {
 public:
  inline UninstallActorRequest() : UninstallActorRequest(nullptr) {}
  ~UninstallActorRequest() override;
  explicit PROTOBUF_CONSTEXPR UninstallActorRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UninstallActorRequest(const UninstallActorRequest& from);
  UninstallActorRequest(UninstallActorRequest&& from) noexcept
    : UninstallActorRequest() {
    *this = ::std::move(from);
  }

  inline UninstallActorRequest& operator=(const UninstallActorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UninstallActorRequest& operator=(UninstallActorRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UninstallActorRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UninstallActorRequest* internal_default_instance() {
    return reinterpret_cast<const UninstallActorRequest*>(
               &_UninstallActorRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(UninstallActorRequest& a, UninstallActorRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UninstallActorRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UninstallActorRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UninstallActorRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UninstallActorRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UninstallActorRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UninstallActorRequest& from) {
    UninstallActorRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UninstallActorRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "actormgr.UninstallActorRequest";
  }
  protected:
  explicit UninstallActorRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActorIdFieldNumber = 2,
    kActorTypeFieldNumber = 1,
  };
  // int64 actor_id = 2;
  void clear_actor_id();
  int64_t actor_id() const;
  void set_actor_id(int64_t value);
  private:
  int64_t _internal_actor_id() const;
  void _internal_set_actor_id(int64_t value);
  public:

  // int32 actor_type = 1;
  void clear_actor_type();
  int32_t actor_type() const;
  void set_actor_type(int32_t value);
  private:
  int32_t _internal_actor_type() const;
  void _internal_set_actor_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:actormgr.UninstallActorRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t actor_id_;
    int32_t actor_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2factor_5fmgr_2eproto;
};
// -------------------------------------------------------------------

class UninstallActorReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:actormgr.UninstallActorReply) */ {
 public:
  inline UninstallActorReply() : UninstallActorReply(nullptr) {}
  ~UninstallActorReply() override;
  explicit PROTOBUF_CONSTEXPR UninstallActorReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UninstallActorReply(const UninstallActorReply& from);
  UninstallActorReply(UninstallActorReply&& from) noexcept
    : UninstallActorReply() {
    *this = ::std::move(from);
  }

  inline UninstallActorReply& operator=(const UninstallActorReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline UninstallActorReply& operator=(UninstallActorReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UninstallActorReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const UninstallActorReply* internal_default_instance() {
    return reinterpret_cast<const UninstallActorReply*>(
               &_UninstallActorReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(UninstallActorReply& a, UninstallActorReply& b) {
    a.Swap(&b);
  }
  inline void Swap(UninstallActorReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UninstallActorReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UninstallActorReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UninstallActorReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UninstallActorReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UninstallActorReply& from) {
    UninstallActorReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UninstallActorReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "actormgr.UninstallActorReply";
  }
  protected:
  explicit UninstallActorReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
    kErrorCodeFieldNumber = 2,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 error_code = 2;
  void clear_error_code();
  int32_t error_code() const;
  void set_error_code(int32_t value);
  private:
  int32_t _internal_error_code() const;
  void _internal_set_error_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:actormgr.UninstallActorReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    int32_t error_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2factor_5fmgr_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreateActorRequest

// int32 actor_type = 1;
inline void CreateActorRequest::clear_actor_type() {
  _impl_.actor_type_ = 0;
}
inline int32_t CreateActorRequest::_internal_actor_type() const {
  return _impl_.actor_type_;
}
inline int32_t CreateActorRequest::actor_type() const {
  // @@protoc_insertion_point(field_get:actormgr.CreateActorRequest.actor_type)
  return _internal_actor_type();
}
inline void CreateActorRequest::_internal_set_actor_type(int32_t value) {
  
  _impl_.actor_type_ = value;
}
inline void CreateActorRequest::set_actor_type(int32_t value) {
  _internal_set_actor_type(value);
  // @@protoc_insertion_point(field_set:actormgr.CreateActorRequest.actor_type)
}

// int64 actor_id = 2;
inline void CreateActorRequest::clear_actor_id() {
  _impl_.actor_id_ = int64_t{0};
}
inline int64_t CreateActorRequest::_internal_actor_id() const {
  return _impl_.actor_id_;
}
inline int64_t CreateActorRequest::actor_id() const {
  // @@protoc_insertion_point(field_get:actormgr.CreateActorRequest.actor_id)
  return _internal_actor_id();
}
inline void CreateActorRequest::_internal_set_actor_id(int64_t value) {
  
  _impl_.actor_id_ = value;
}
inline void CreateActorRequest::set_actor_id(int64_t value) {
  _internal_set_actor_id(value);
  // @@protoc_insertion_point(field_set:actormgr.CreateActorRequest.actor_id)
}

// -------------------------------------------------------------------

// CreateActorReply

// bool success = 1;
inline void CreateActorReply::clear_success() {
  _impl_.success_ = false;
}
inline bool CreateActorReply::_internal_success() const {
  return _impl_.success_;
}
inline bool CreateActorReply::success() const {
  // @@protoc_insertion_point(field_get:actormgr.CreateActorReply.success)
  return _internal_success();
}
inline void CreateActorReply::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void CreateActorReply::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:actormgr.CreateActorReply.success)
}

// int32 error_code = 2;
inline void CreateActorReply::clear_error_code() {
  _impl_.error_code_ = 0;
}
inline int32_t CreateActorReply::_internal_error_code() const {
  return _impl_.error_code_;
}
inline int32_t CreateActorReply::error_code() const {
  // @@protoc_insertion_point(field_get:actormgr.CreateActorReply.error_code)
  return _internal_error_code();
}
inline void CreateActorReply::_internal_set_error_code(int32_t value) {
  
  _impl_.error_code_ = value;
}
inline void CreateActorReply::set_error_code(int32_t value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:actormgr.CreateActorReply.error_code)
}

// -------------------------------------------------------------------

// FindActorRequest

// int32 actor_type = 1;
inline void FindActorRequest::clear_actor_type() {
  _impl_.actor_type_ = 0;
}
inline int32_t FindActorRequest::_internal_actor_type() const {
  return _impl_.actor_type_;
}
inline int32_t FindActorRequest::actor_type() const {
  // @@protoc_insertion_point(field_get:actormgr.FindActorRequest.actor_type)
  return _internal_actor_type();
}
inline void FindActorRequest::_internal_set_actor_type(int32_t value) {
  
  _impl_.actor_type_ = value;
}
inline void FindActorRequest::set_actor_type(int32_t value) {
  _internal_set_actor_type(value);
  // @@protoc_insertion_point(field_set:actormgr.FindActorRequest.actor_type)
}

// int64 actor_id = 2;
inline void FindActorRequest::clear_actor_id() {
  _impl_.actor_id_ = int64_t{0};
}
inline int64_t FindActorRequest::_internal_actor_id() const {
  return _impl_.actor_id_;
}
inline int64_t FindActorRequest::actor_id() const {
  // @@protoc_insertion_point(field_get:actormgr.FindActorRequest.actor_id)
  return _internal_actor_id();
}
inline void FindActorRequest::_internal_set_actor_id(int64_t value) {
  
  _impl_.actor_id_ = value;
}
inline void FindActorRequest::set_actor_id(int64_t value) {
  _internal_set_actor_id(value);
  // @@protoc_insertion_point(field_set:actormgr.FindActorRequest.actor_id)
}

// -------------------------------------------------------------------

// FindActorReply

// bool found = 1;
inline void FindActorReply::clear_found() {
  _impl_.found_ = false;
}
inline bool FindActorReply::_internal_found() const {
  return _impl_.found_;
}
inline bool FindActorReply::found() const {
  // @@protoc_insertion_point(field_get:actormgr.FindActorReply.found)
  return _internal_found();
}
inline void FindActorReply::_internal_set_found(bool value) {
  
  _impl_.found_ = value;
}
inline void FindActorReply::set_found(bool value) {
  _internal_set_found(value);
  // @@protoc_insertion_point(field_set:actormgr.FindActorReply.found)
}

// int32 remote_type = 2;
inline void FindActorReply::clear_remote_type() {
  _impl_.remote_type_ = 0;
}
inline int32_t FindActorReply::_internal_remote_type() const {
  return _impl_.remote_type_;
}
inline int32_t FindActorReply::remote_type() const {
  // @@protoc_insertion_point(field_get:actormgr.FindActorReply.remote_type)
  return _internal_remote_type();
}
inline void FindActorReply::_internal_set_remote_type(int32_t value) {
  
  _impl_.remote_type_ = value;
}
inline void FindActorReply::set_remote_type(int32_t value) {
  _internal_set_remote_type(value);
  // @@protoc_insertion_point(field_set:actormgr.FindActorReply.remote_type)
}

// -------------------------------------------------------------------

// UninstallActorRequest

// int32 actor_type = 1;
inline void UninstallActorRequest::clear_actor_type() {
  _impl_.actor_type_ = 0;
}
inline int32_t UninstallActorRequest::_internal_actor_type() const {
  return _impl_.actor_type_;
}
inline int32_t UninstallActorRequest::actor_type() const {
  // @@protoc_insertion_point(field_get:actormgr.UninstallActorRequest.actor_type)
  return _internal_actor_type();
}
inline void UninstallActorRequest::_internal_set_actor_type(int32_t value) {
  
  _impl_.actor_type_ = value;
}
inline void UninstallActorRequest::set_actor_type(int32_t value) {
  _internal_set_actor_type(value);
  // @@protoc_insertion_point(field_set:actormgr.UninstallActorRequest.actor_type)
}

// int64 actor_id = 2;
inline void UninstallActorRequest::clear_actor_id() {
  _impl_.actor_id_ = int64_t{0};
}
inline int64_t UninstallActorRequest::_internal_actor_id() const {
  return _impl_.actor_id_;
}
inline int64_t UninstallActorRequest::actor_id() const {
  // @@protoc_insertion_point(field_get:actormgr.UninstallActorRequest.actor_id)
  return _internal_actor_id();
}
inline void UninstallActorRequest::_internal_set_actor_id(int64_t value) {
  
  _impl_.actor_id_ = value;
}
inline void UninstallActorRequest::set_actor_id(int64_t value) {
  _internal_set_actor_id(value);
  // @@protoc_insertion_point(field_set:actormgr.UninstallActorRequest.actor_id)
}

// -------------------------------------------------------------------

// UninstallActorReply

// bool success = 1;
inline void UninstallActorReply::clear_success() {
  _impl_.success_ = false;
}
inline bool UninstallActorReply::_internal_success() const {
  return _impl_.success_;
}
inline bool UninstallActorReply::success() const {
  // @@protoc_insertion_point(field_get:actormgr.UninstallActorReply.success)
  return _internal_success();
}
inline void UninstallActorReply::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void UninstallActorReply::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:actormgr.UninstallActorReply.success)
}

// int32 error_code = 2;
inline void UninstallActorReply::clear_error_code() {
  _impl_.error_code_ = 0;
}
inline int32_t UninstallActorReply::_internal_error_code() const {
  return _impl_.error_code_;
}
inline int32_t UninstallActorReply::error_code() const {
  // @@protoc_insertion_point(field_get:actormgr.UninstallActorReply.error_code)
  return _internal_error_code();
}
inline void UninstallActorReply::_internal_set_error_code(int32_t value) {
  
  _impl_.error_code_ = value;
}
inline void UninstallActorReply::set_error_code(int32_t value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:actormgr.UninstallActorReply.error_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace actormgr

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpc_2factor_5fmgr_2eproto
