package pool_template

var poolServiceTemplateStr = `// Code generated by TX.
// Template: List logic

package {{.PoolPackage}}

import (
{{- range .PoolImports 1 }}
    {{.}}
{{- end}}
)

type {{.SystemName}}DBPoolImpl struct{
    {{- range .PoolFields}}
    {{- $structName := CamelizeStr .TableName .SystemName}}
    {{$structName}}Pool *sync.Pool
    {{- end}}
}

var _dbPool *{{.SystemName}}DBPoolImpl

func {{.SystemName}}DBPool() *{{.SystemName}}DBPoolImpl {
    return _dbPool
}

func Init{{.SystemName}}DBPool() *{{.SystemName}}DBPoolImpl {
    _dbPool = &{{.SystemName}}DBPoolImpl{
{{- range .PoolFields}}
{{- $structName := CamelizeStr .TableName .SystemName}}
        {{$structName}}Pool: &sync.Pool{
                New: func() interface{} {
                    return {{.TypePackage}}.DBNew{{$structName}}()
                },
            },
{{- end}}
    }
    return _dbPool
}
`
