package pool_template

var poolFuncTemplateStr = `// Code generated by TX.
// Template: List logic

package {{.PoolPackage}}

import (
{{- range .PoolImports 0 }}
    {{.}}
{{- end}}
)

{{- range .PoolFields}}
{{$structName := CamelizeStr .TableName .SystemName}}
func Get{{$structName}}() *{{.TypePackage}}.{{$structName}} {
    return _dbPool.{{$structName}}Pool.Get().(*{{.TypePackage}}.{{$structName}})
}

func Put{{$structName}}(info *{{.TypePackage}}.{{$structName}}) {
    if info != nil {
        _dbPool.{{$structName}}Pool.Put(info.Clean())
    }
}
{{- end}}
`
