#!/bin/bash

echo " ===>>> enter AllianceServer dir"
cd ./AllianceServer
make clean
cd ..

echo " ===>>> enter AllianceServerC dir"
cd ./AllianceServerC
make clean
cd ..

echo " ===>>> enter FriendServer dir"
cd ./FriendServer
make clean
cd ..

echo " ===>>> enter FriendServerC dir"
cd ./FriendServerC
make clean
cd ..

echo " ===>>> enter GameServer dir"
cd ./GameServer
make clean
cd ..

echo " ===>>> enter TransferServer dir"
cd ./TransferServer
make clean
cd ..

echo " ===>>> enter WorldServer dir"
cd ./WorldServer
make clean
cd ..

echo " ===>>> enter RegServer dir"
cd ./RegServer
make clean
cd ..

echo " ===>>> enter LoginServer dir"
cd ./LoginServer
make clean
cd ..
