#!/bin/bash

echo " ===>>> enter AllianceServer dir"
cd ./AllianceServer
make
cd ..

echo " ===>>> enter AllianceServerC dir"
cd ./AllianceServerC
make
cd ..

echo " ===>>> enter FriendServer dir"
cd ./FriendServer
make
cd ..

echo " ===>>> enter FriendServerC dir"
cd ./FriendServerC
make
cd ..

echo " ===>>> enter GameServer dir"
cd ./GameServer
make
cd ..

echo " ===>>> enter TransferServer dir"
cd ./TransferServer
make
cd ..

echo " ===>>> enter WorldServer dir"
cd ./WorldServer
make
cd ..

