#pragma once

#include "rpc/actor_mgr.grpc.pb.h"
#include "xBase/xSingleton.h"

// ActorMgrServiceImpl — gRPC service bridging cross-process actor management.
//
// Registered with SRpcService at startup, it accepts remote CreateActor,
// FindActor, and UninstallActor requests and delegates to the local
// ActorCreator and CActorMgr singletons.
//
// This is the server-side handler; client calls go through
// ActorMgrService::Stub (auto-generated by gRPC).
//
// Registration (before SRpcService::Start):
//   static ActorMgrServiceImpl svc;
//   SRpcService::getMe().RegistService(&svc);

class ActorMgrServiceImpl final : public actormgr::ActorMgrService::Service
{
public:
    ActorMgrServiceImpl()  = default;
    ~ActorMgrServiceImpl() = default;

    // Create an actor locally.
    // The remote process sends (actor_type, actor_id); we delegate to
    // ActorCreator::Create → CActorMgr::AddInstance → CActorMgr::Install.
    ::grpc::Status CreateActor(::grpc::ServerContext* context,
        const ::actormgr::CreateActorRequest* request,
        ::actormgr::CreateActorReply* reply) override;

    // Query whether this process hosts a specific actor.
    ::grpc::Status FindActor(::grpc::ServerContext* context,
        const ::actormgr::FindActorRequest* request,
        ::actormgr::FindActorReply* reply) override;

    // Uninstall (remove) an actor from this process.
    ::grpc::Status UninstallActor(::grpc::ServerContext* context,
        const ::actormgr::UninstallActorRequest* request,
        ::actormgr::UninstallActorReply* reply) override;
};
