#include "LuaVM.h"
#include "xLog/xLog.h"
#include <string>
#include <filesystem>

// Forward declaration of SWIG's module init function.
// Generated by SWIG in luacore_wrap.cxx, this function
// creates the global "luacore" table with all si_* functions.
extern "C" int luaopen_luacore(lua_State* L);

// -------------------------------------------------------------------
// LuaVM Implementation
// -------------------------------------------------------------------

LuaVM::LuaVM() {}

LuaVM::~LuaVM() {
    Release();
}

bool LuaVM::Init(const std::string& strScriptRoot) {
    XLOG("[INIT] LuaVM initializing with script root: %s", strScriptRoot.c_str());
    m_strScriptRoot = strScriptRoot;

    // Create the Lua state
    m_pL = luaL_newstate();
    if (!m_pL) {
        XERR("[LuaVM] Failed to create Lua state");
        return false;
    }

    // Load all standard Lua libraries
    luaL_openlibs(m_pL);

    // Set Lua's module search path to include our script directories.
    std::string pathCmd =
        "package.path = package.path"
        " .. ';" + strScriptRoot + "/?.lua'"
        " .. ';" + strScriptRoot + "/common/?.lua'"
        " .. ';" + strScriptRoot + "/common/util/?.lua'"
        " .. ';" + strScriptRoot + "/common/actor/?.lua'"
        " .. ';" + strScriptRoot + "/actors/?.lua'"
        " .. ';" + strScriptRoot + "/actors/?/?.lua'";
    luaL_dostring(m_pL, pathCmd.c_str());

    // Initialize the SWIG module (registers all si_* functions)
    if (!InitLuacoreModule()) {
        XERR("[LuaVM] Failed to initialize luacore module");
        return false;
    }

    // Load the xEngine global module framework.
    // This registers all common modules (Log, Timer, StringExt, Class,
    // ActorBase, ActorMgr, Redis, DB, RPC) into the global xEngine table.
    // Re-executing this file performs a hot-reload of all common modules.
    if (!DoFile(m_strScriptRoot + "/common/include.lua")) {
        XERR("[LuaVM] Failed to load common/include.lua");
        return false;
    }

    return true;
}

bool LuaVM::InitLuacoreModule() {
    if (!m_pL) {
        return false;
    }

    // Load the SWIG-generated luacore module.
    // This creates the global "luacore" table with all wrapped C++ types
    // and si_* functions (si_log_*, si_time_*, si_str_*, si_actor_*, etc.).
    luaopen_luacore(m_pL);

    XLOG("[LuaVM] SWIG luacore module initialized (si_* functions registered)");
    return true;
}

bool LuaVM::DoFile(const std::string& strFilePath) {
    if (!m_pL) {
        XERR("[LuaVM] Lua state not initialized");
        return false;
    }

    if (luaL_dofile(m_pL, strFilePath.c_str()) != LUA_OK) {
        XERR("[LuaVM] Error executing '%s': %s",
             strFilePath.c_str(),
             lua_tostring(m_pL, -1));
        lua_pop(m_pL, 1);  // pop error message
        return false;
    }
    return true;
}

bool LuaVM::DoString(const std::string& strCode) {
    if (!m_pL) {
        XERR("[LuaVM] Lua state not initialized");
        return false;
    }

    if (luaL_dostring(m_pL, strCode.c_str()) != LUA_OK) {
        XERR("[LuaVM] Error executing string: %s",
             lua_tostring(m_pL, -1));
        lua_pop(m_pL, 1);  // pop error message
        return false;
    }
    return true;
}

int32 LuaVM::LoadAllActors(const std::string& strPlatform) {
    if (!m_pL) {
        XERR("[LuaVM] Lua state not initialized");
        return 0;
    }

    std::string baseDir = m_strScriptRoot + "/" + strPlatform;
    int32 count = 0;

    try {
        for (const auto& entry : std::filesystem::directory_iterator(baseDir)) {
            if (!entry.is_directory()) continue;

            std::string initPath = entry.path().string() + "/init.lua";
            if (std::filesystem::exists(initPath)) {
                XLOG("[LuaVM] Loading actor: %s", initPath.c_str());
                if (DoFile(initPath)) {
                    count++;
                }
            }
        }
    } catch (const std::exception& e) {
        XERR("[LuaVM] Failed to traverse directory '%s': %s", baseDir.c_str(), e.what());
    }

    XLOG("[LuaVM] Loaded %d actor(s) from platform=%s", count, strPlatform.c_str());
    return count;
}

void LuaVM::Release() {
    if (m_pL) {
        lua_close(m_pL);
        m_pL = nullptr;
        XLOG("[LuaVM] Lua state released");
    }
}
