-- init.lua — Gate actor config (prod)
require("common.include")
require("actors.gate.gate")
require("actors.gate.net_msg.include")
require("actors.gate.on_event.include")
require("actors.gate.on_rpc.include")
xEngine.Log.info("[Gate:prod] ready")
