package redis_template

var RedisFileTStr = `// Code generated by TX.
// Template: Redis File logic

package {{.LogicPackage}}
{{ if .LogicImports }}
import (
{{- range .LogicImports}}
    {{.}}
{{- end}}
){{end}}

`
