package pool_template

var FuncTemplateStr = `// Code generated by TX.
// Template: Proto Server Handler

package {{.LogicPackage}}
{{ if .FuncImports }}
import (
{{- range .FuncImports}}
    {{.}}
{{- end}}
){{- end}}
{{ range .Entities}}
func Get{{.FuncName}}() *{{.FiledDataType}} {
    return _{{.PoolValue}}.{{.FieldName}}Pool.Get().(*{{.FiledDataType}})
}

func Put{{.FuncName}}(info *{{.FiledDataType}}) {
    info.Clean()
    _{{.PoolValue}}.{{.FieldName}}Pool.Put(info)
}
{{ end}}
`
