package pool_template

var ImplTemplateStr = `// Code generated by TX.
// Template: Proto Server Handler

package {{.LogicPackage}}
{{ if .LogicImports }}
import (
{{- range .LogicImports}}
    {{.}}
{{- end}}
){{end}}

type {{.PoolName}}Impl struct {
{{- range .Entities}}
    {{.FieldName}}Pool      *sync.Pool
{{- end}}
}

var _{{.PoolValue}} *{{.PoolName}}Impl

func Get{{.PoolName}}Impl() *{{.PoolName}}Impl {
    return _{{.PoolValue}}
}

func New{{.PoolName}}Impl() *{{.PoolName}}Impl {
    if _{{.PoolValue}} == nil {
        _{{.PoolValue}} = &{{.PoolName}}Impl{
        {{- range .Entities}}
            {{.FieldName}}Pool: &sync.Pool{
                New: func() interface{} {
                    return &{{.FiledDataType}}{}
                },
            },
        {{- end}}
        }
    }
    return _{{.PoolValue}}
}`
