package nats_template

var natsTemplateStr = `// Code generated by TX.
// Template: Nats Init Proto

package nats_proto

import (
    "errors"

{{- range .NatsImports}}
    {{.}}
{{- end}}
)

func InitNatsProtoMessage(s txinter.INatsService) error {
    if s == nil {
        return errors.New("InitNatsProtoMessage error, INatsService is nil")
    }
    //-----------------Proto Register------------------
{{- range .NatsCommands}}
    s.RegisterProtoMsg(uint16({{.Package}}.{{.CmdName}}), {{.Package}}.{{.ProtoName}}{})
{{- end}}

    return nil
}
`
