-- init.lua — Player actor config (test)
require("common.include")
require("actors.player.player")
require("actors.player.on_event.include")
require("actors.player.on_rpc.include")
xEngine.Log.info("[Player:test] ready")
