#!/bin/bash

echo " ===>>> enter xBase dir"
cd ./xBase
make clean
cd ..

echo " ===>>> enter xCommand dir"
cd ./xCommand
make clean
cd ..

echo " ===>>> enter xNet dir"
cd ./xNet
make clean
cd ..

echo " ===>>> enter xServer dir"
cd ./xServer
make clean
cd ..

#echo " ===>>> enter xGameData dir"
#cd ./xGameData
#make clean
#cd ..

#echo " ===>>> enter xGame dir"
#cd ./xGame
#make clean
#cd ..

#echo " ===>>> enter xConfig dir"
#cd ./xConfig
#make clean
#cd ..
