#!/bin/bash

echo " ===>>> enter xBase dir"
cd ./xBase
make
cd ..

echo " ===>>> enter xCommand dir"
cd ./xCommand
make
cd ..

echo " ===>>> enter xNet dir"
cd ./xNet
make
cd ..

echo " ===>>> enter xServer dir"
cd ./xServer
make
cd ..

#echo " ===>>> enter xGameData dir"
#cd ./xGameData
#make
#cd ..

#echo " ===>>> enter xConfig dir"
#cd ./xConfig
#make
#cd ..

#echo " ===>>> enter xGame dir"
#cd ./xGame
#make
#cd ..



